# Generated by Django 6.0.2 on 2026-02-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike', '0002_remove_category_description_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nike.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nike.user')),
            ],
        ),
    ]
