# Generated by Django 6.0.2 on 2026-02-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
    ]
